.TH P2ADA 1 "30 April 2003" P2ADA "Linux Programmer's Manual"
.SH NAME
p2ada \- (Delphi) Pascal to Ada translator
.SH SYNOPSIS
.B p2ada
[
.I input_file
] {
.BI -I imports
} [
.BI -E exports
]
.SH DESCRIPTION
.I p2ada
is a Borland (Delphi) Pascal to Ada 95 translator. Input is taken from the named
.I input_file
(or from standard input if no file is named) and the output is written to standard
output.
.SH OPTIONS
.TP
.BI \-I imports
Read the imports from the file
.IR imports .
.TP
.BI \-E exports
Write a file
.I exports
with the definitions of: the interface part of the Borland/UCSD Pascal unit; the export
part of an ISO Pascal module (this not yet implemented); and the top-level definitions
of a program, considered as a code snippet.
.SH SEE ALSO
.IR http://www.mysunrise.ch/users/gdm/gsoft.htm " The web page of Gautier de Montmollin"
.sp
.IR gnat (1)
